### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by GitNitneroc** [ShirosakiMieru/NetherUpdater#1]
Sorry, this probably sounds really dumb, but I'd really like to try this plugin but I could not install it.

Do you provide a built download, or should I build it myself ? Did I miss some piece of information ?

Thank you very much for your help

**Comment by ShirosakiMieru** [comment]
You can download the compiled plugin on [release page](https://github.com/ShirosakiMieru/NetherUpdater/releases).

**Comment by GitNitneroc** [comment]
Omg... Did I really miss that? I was tired, but I really feel stupid...
Excuse me.

Le mer. 22 juil. 2020 à 07:30, ShirosakiMieru <notifications@github.com> a
écrit :
